//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: 407.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_407_H__
#define __WDR_407_H__

#ifdef __GNUG__
    #pragma interface "407_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_LISTCTRL 10000
#define ID_LINE 10001
#define ID_TEXT 10002
#define ID_COMBO 10003
#define ID_ROT_BOX 10004
#define ID_ORB 10005
#define ID_STAB 10006
#define ID_HTML 10007
#define ID_GLCANVAS 10008
wxSizer *MainPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
